# Generated by Django 4.1 on 2023-03-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='name_f',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
